Oop lvl2
sintsovamy/phpstudy pull request #3
Opened 2023-10-26 15:58 UTC by sintsovamy

2023-10-29 01:14 UTC, RetmixX requested changes
Поправить замечания. На будущее, не стоит на все писать комментарии, это приводит так же к избыточности кода и трудности чтения. Лучше комментарии оставлять там, с первого раза тяжело понять логику работы кода.

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var string $columnsViaSemicolon*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var string $columnsViaSemicolon*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var string $paramsNamesViaSemicolon*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var string $sql*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var Db $db*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +     * @param array $mappedProperties
Указать какие объекты в массиве будут

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +        /* @var array $columns2params*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var array $params2values*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var int $index*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	    /* @var string $param*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/*@var string $sql*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/*@var Db $db*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	$sql = 'UPDATE ' . static::getTableName() . ' SET ' . implode(', ', $columns2params) . ' WHERE id = ' . $this->id;
Бинди идшник, а не строчки складывай.

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +     * return array
Массив с какими объектами?

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +        /* @var \ReflectionObject $reflector*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	/* @var array $properties*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +        /* @var array $mappedProperties*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +            /* @var string $propertyName*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +	    /* @var string $propertyNameAsUnderscore*/
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +     *
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/ActiveRecordEntity.php
> +    /**
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +    /** @var int*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @var User $author
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @return string
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @return string
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @return string
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @return User
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +    /**
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Articles/Article.php
> +     * @param $name
А в чем смысл коммента, если в нем только название параметра без типа данных, когда в сигнатуре метода у тебя все указано

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var bool*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +    /** @var string*/
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +     * @return string
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Models/Users/User.php
> +     * @return string
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +    /** @var \PDO */
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +    /** @var \PDO */
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +    private static $instance;
Интстансу тип данных добавь

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +                'pgsql:host=' . $dbOptions['host'] . ';dbname=' . $dbOptions['dbname'], $dbOptions['user'], $dbOptions['password']);
В пхп придумали специальный синтаксис, для внедрения динамических переменных в строку:
$name = 'Retmix';
$age = 20;
$textHello = "Name -  {$name}. Age - {$age}";

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +     * @return Db
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +    /**
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/Services/Db.php
> +     * @return int
!

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/View/View.php
> +    /** @var string */
Тип из коммента в поле

2023-10-29 01:14 UTC, RetmixX commented on src/MyProject/View/View.php
> +     * @param string $templateName
!

2023-10-29 15:33 UTC, jurapro requested changes
Андрей все по делу написал. Исправляй и ок будет

2023-10-31 01:57 UTC, jurapro approved these changes
принято

2023-10-31 03:04 UTC, RetmixX approved these changes

2023-10-31 15:57 UTC, merged